config/routes.rb
Prim::Application.routes.draw do
  resources :product_categories

  resources :cetegories

  resources :products

  resources :product_attributes

  resources :attributes

  resources :product_types

end

app/models/product_attribute.rb
class ProductAttribute < ActiveRecord::Base
end

app/controllers/product_attributes_controller.rb
class ProductAttributesController < ApplicationController
  before_action :set_product_attribute, only: [:show, :edit, :update, :destroy]

  # GET /product_attributes
  # GET /product_attributes.json
  def index
    @product_attributes = ProductAttribute.all
  end

  # GET /product_attributes/1
  # GET /product_attributes/1.json
  def show
  end

  # GET /product_attributes/new
  def new
    @product_attribute = ProductAttribute.new
  end

  # GET /product_attributes/1/edit
  def edit
  end

  # POST /product_attributes
  # POST /product_attributes.json
  def create
    @product_attribute = ProductAttribute.new(product_attribute_params)

    respond_to do |format|
      if @product_attribute.save
        format.html { redirect_to @product_attribute, notice: 'Product attribute was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product_attribute }
      else
        format.html { render action: 'new' }
        format.json { render json: @product_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_attributes/1
  # PATCH/PUT /product_attributes/1.json
  def update
    respond_to do |format|
      if @product_attribute.update(product_attribute_params)
        format.html { redirect_to @product_attribute, notice: 'Product attribute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_attributes/1
  # DELETE /product_attributes/1.json
  def destroy
    @product_attribute.destroy
    respond_to do |format|
      format.html { redirect_to product_attributes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_attribute
      @product_attribute = ProductAttribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_attribute_params
      params.require(:product_attribute).permit(:product_id, :attribute_id, :locale, :value)
    end
end

app/helpers/product_attributes_helper.rb
module ProductAttributesHelper
end

app/views/product_attributes/_form.html.erb
<%= form_for(@product_attribute) do |f| %>
  <% if @product_attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_attribute.errors.count, "error") %> prohibited this product_attribute from being saved:</h2>

      <ul>
      <% @product_attribute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :attribute_id %><br>
    <%= f.number_field :attribute_id %>
  </div>
  <div class="field">
    <%= f.label :locale %><br>
    <%= f.text_field :locale %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_attributes/edit.html.erb
<h1>Editing product_attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_attribute %> |
<%= link_to 'Back', product_attributes_path %>

app/views/product_attributes/index.html.erb
<h1>Listing product_attributes</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Attribute</th>
      <th>Locale</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @product_attributes.each do |product_attribute| %>
      <tr>
        <td><%= product_attribute.product_id %></td>
        <td><%= product_attribute.attribute_id %></td>
        <td><%= product_attribute.locale %></td>
        <td><%= product_attribute.value %></td>
        <td><%= link_to 'Show', product_attribute %></td>
        <td><%= link_to 'Edit', edit_product_attribute_path(product_attribute) %></td>
        <td><%= link_to 'Destroy', product_attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product attribute', new_product_attribute_path %>

app/views/product_attributes/new.html.erb
<h1>New product_attribute</h1>

<%= render 'form' %>

<%= link_to 'Back', product_attributes_path %>

app/views/product_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product_attribute.product_id %>
</p>

<p>
  <strong>Attribute:</strong>
  <%= @product_attribute.attribute_id %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @product_attribute.locale %>
</p>

<p>
  <strong>Value:</strong>
  <%= @product_attribute.value %>
</p>

<%= link_to 'Edit', edit_product_attribute_path(@product_attribute) %> |
<%= link_to 'Back', product_attributes_path %>