config/routes.rb
Prim::Application.routes.draw do
  resources :product_categories

  resources :cetegories

  resources :products

  resources :product_attributes

  resources :attributes

  resources :product_types

end

app/models/cetegory.rb
class Cetegory < ActiveRecord::Base
end

app/controllers/cetegories_controller.rb
class CetegoriesController < ApplicationController
  before_action :set_cetegory, only: [:show, :edit, :update, :destroy]

  # GET /cetegories
  # GET /cetegories.json
  def index
    @cetegories = Cetegory.all
  end

  # GET /cetegories/1
  # GET /cetegories/1.json
  def show
  end

  # GET /cetegories/new
  def new
    @cetegory = Cetegory.new
  end

  # GET /cetegories/1/edit
  def edit
  end

  # POST /cetegories
  # POST /cetegories.json
  def create
    @cetegory = Cetegory.new(cetegory_params)

    respond_to do |format|
      if @cetegory.save
        format.html { redirect_to @cetegory, notice: 'Cetegory was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cetegory }
      else
        format.html { render action: 'new' }
        format.json { render json: @cetegory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cetegories/1
  # PATCH/PUT /cetegories/1.json
  def update
    respond_to do |format|
      if @cetegory.update(cetegory_params)
        format.html { redirect_to @cetegory, notice: 'Cetegory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cetegory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cetegories/1
  # DELETE /cetegories/1.json
  def destroy
    @cetegory.destroy
    respond_to do |format|
      format.html { redirect_to cetegories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cetegory
      @cetegory = Cetegory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cetegory_params
      params.require(:cetegory).permit(:name, :catID, :parentCatID, :isRoot)
    end
end

app/helpers/cetegories_helper.rb
module CetegoriesHelper
end

app/views/cetegories/_form.html.erb
<%= form_for(@cetegory) do |f| %>
  <% if @cetegory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cetegory.errors.count, "error") %> prohibited this cetegory from being saved:</h2>

      <ul>
      <% @cetegory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :catID %><br>
    <%= f.text_field :catID %>
  </div>
  <div class="field">
    <%= f.label :parentCatID %><br>
    <%= f.text_field :parentCatID %>
  </div>
  <div class="field">
    <%= f.label :isRoot %><br>
    <%= f.check_box :isRoot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cetegories/edit.html.erb
<h1>Editing cetegory</h1>

<%= render 'form' %>

<%= link_to 'Show', @cetegory %> |
<%= link_to 'Back', cetegories_path %>

app/views/cetegories/index.html.erb
<h1>Listing cetegories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Catid</th>
      <th>Parentcatid</th>
      <th>Isroot</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cetegories.each do |cetegory| %>
      <tr>
        <td><%= cetegory.name %></td>
        <td><%= cetegory.catID %></td>
        <td><%= cetegory.parentCatID %></td>
        <td><%= cetegory.isRoot %></td>
        <td><%= link_to 'Show', cetegory %></td>
        <td><%= link_to 'Edit', edit_cetegory_path(cetegory) %></td>
        <td><%= link_to 'Destroy', cetegory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cetegory', new_cetegory_path %>

app/views/cetegories/new.html.erb
<h1>New cetegory</h1>

<%= render 'form' %>

<%= link_to 'Back', cetegories_path %>

app/views/cetegories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cetegory.name %>
</p>

<p>
  <strong>Catid:</strong>
  <%= @cetegory.catID %>
</p>

<p>
  <strong>Parentcatid:</strong>
  <%= @cetegory.parentCatID %>
</p>

<p>
  <strong>Isroot:</strong>
  <%= @cetegory.isRoot %>
</p>

<%= link_to 'Edit', edit_cetegory_path(@cetegory) %> |
<%= link_to 'Back', cetegories_path %>